#include "../../include/math/numerical.h"
#include <random>

namespace numerical
{
    double randomDouble() {
        // https://stackoverflow.com/questions/9878965/rand-between-0-and-1
        std::random_device rd;  //Will be used to obtain a seed for the random number engine
        std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
        std::uniform_real_distribution<> dis(0, 1);

        return dis(gen); // Use dis to transform the random unsigned int generated by gen into a double in [0, 1).
    }
}